name: Pull Request Merged to Main

on:
  push:
    branches:
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
        # use v2 instead of v2.0.0 !!
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }} 
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          SLACK_MESSAGE: ${{ github.repository }} 
          SLACK_COLOR: '#00FF00'